import { Metadata } from 'next/head';
import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';  // Import Head from next/head
import Navbar from '@/components/Navigation/Navbar';
import Sidebar from '@/components/Navigation/Sidebar';
import Footer from '@/components/Footer/Footer';
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Other head elements go here */}
      </Head>

      <body className={inter.className}>
        <Script src="https://demo.themesberg.com/windster/app.bundle.js"></Script>
        <Script src="https://buttons.github.io/buttons.js"></Script>
        <Navbar />
        <main className="flex overflow-hidden bg-white pt-16">
          <div className="bg-gray-900 opacity-50 hidden fixed inset-0 z-10" id="sidebarBackdrop"></div>
          <Sidebar />
          <div id="main-content" className="h-full w-full bg-gray-50 relative overflow-y-auto lg:ml-64">
            {children}
            <Footer />
            <p className="text-center text-sm text-gray-500 my-10">
              &copy; @2024 <a href="#" className="hover:underline" target="_blank">Noel Osiro</a>. All rights reserved.
            </p>
          </div>
        </main>
      </body>
    </>
  );
};

export default RootLayout;
