import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
import Navbar from '@/components/Navigation/Navbar';
import Sidebar from '@/components/Navigation/Sidebar';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex overflow-hidden bg-white pt-16">
          <Sidebar />
          <div className="bg-gray-900 opacity-50 hidden fixed inset-0 z-10" id="sidebarBackdrop"></div>
          <div id="main-content" className="h-full w-full bg-gray-50 relative overflow-y-auto lg:ml-64">
          {children}
          <Footer/>
          <p className="text-center text-sm text-gray-500 my-10">
            &copy; @2024 <a href="#" className="hover:underline" target="_blank">Noel Osiro</a>. All rights reserved.
         </p>
          </div>
        </div>
      </body>
    </html>
  )
}
